#!/usr/bin/env python3
"""Write each capability's committed `.env` from the schema in its declaration.

A capability declares its settings once, in `config:`. This renders that into the `.env`
beside it — the key, what it is for, its default, and the environment variable that
overrides it. You never edit that file; you put your values in `.env.local` next to it.

Generating it is the point. A hand-written template drifts from the schema within a month,
because nobody edits the template when they add a key to the file they are actually using.

    make env-template            # write them
    make env-template ARGS=--check   # fail if any is out of date (runs in `make lint`)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

from harry.config import env_key

SUMMARY = (__doc__ or '').partition('\n')[0]

ROOT = Path(__file__).parent.parent
HARRY = ROOT / '.harry'
KINDS = (('connectors', 'CONNECTOR.md'), ('tools', 'TOOL.md'), ('jobs', 'JOB.md'))

HEADER = """\
# {name} — {description}
#
# GENERATED by `make env-template` from {source}. Do not edit this file.
#
# Your values go in `.env.local` beside it, which is gitignored. Put in only what
# differs — everything else still comes from here, and from the defaults in the
# declaration. Any key can also be overridden from the environment, which is how a
# container injects one; the override name is noted beside each key.
"""


def declarations() -> list[tuple[Path, str]]:
    found = []
    for kind, filename in KINDS:
        directory = HARRY / kind
        for path in sorted(directory.glob(f'*/{filename}')) if directory.is_dir() else []:
            found.append((path, filename))
    return found


def frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding='utf-8')
    if not text.startswith('---'):
        return {}
    block = text.partition('---\n')[2].partition('\n---')[0]
    loaded = yaml.safe_load(block)
    return loaded if isinstance(loaded, dict) else {}


def render(path: Path, filename: str, fields: dict[str, Any]) -> str:
    name = str(fields.get('name', path.parent.name))
    config: dict[str, Any] = fields.get('config') or {}

    lines = [HEADER.format(name=name, description=fields.get('description', ''), source=filename)]
    for key, spec in config.items():
        spec = spec or {}
        lines.append('')
        lines.append(f'# {spec.get("description", "")}')

        notes = []
        if spec.get('required'):
            notes.append('required')
        if spec.get('secret'):
            notes.append('SECRET — leave empty here, set it in .env.local')
        if 'default' in spec and not spec.get('secret'):
            notes.append(f'default: {spec["default"]!r}')
        if notes:
            lines.append(f'#   {" · ".join(notes)}')
        lines.append(f'#   override: {env_key(name, key)}')

        default = spec.get('default')
        value = '' if spec.get('secret') or default is None or isinstance(default, (list, dict)) else default
        lines.append(f'{key.upper()}={value}')

    return '\n'.join(lines) + '\n'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog='env_template.py', description=SUMMARY)
    parser.add_argument('--check', action='store_true', help='fail if any file is out of date')
    args = parser.parse_args(argv)

    stale: list[str] = []
    written = 0
    for path, filename in declarations():
        fields = frontmatter(path)
        if not fields.get('config'):
            continue
        target = path.parent / '.env'
        wanted = render(path, filename, fields)
        current = target.read_text(encoding='utf-8') if target.exists() else None

        if current == wanted:
            continue
        if args.check:
            stale.append(f'{target.relative_to(ROOT)}: {"out of date" if current else "missing"}')
            continue
        target.write_text(wanted, encoding='utf-8')
        written += 1
        print(f'  wrote {target.relative_to(ROOT)}')

    if stale:
        print(f'{len(stale)} generated file(s) do not match their declaration:\n', file=sys.stderr)
        for line in stale:
            print(f'  {line}', file=sys.stderr)
        print('\nRun: make env-template', file=sys.stderr)
        return 1

    print(f'✓ {written} written' if written else '✓ every capability .env matches its declaration')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
